[platformio]
default_envs = release
src_dir = ..

[env:stm32f407ve_base]
platform = ststm32
board = genericSTM32F407VET6
framework = cmsis
upload_protocol = stlink
debug_tool = stlink
debug_speed = 10000

; 直接复用现有目录结构，不复制源码
build_src_filter =
    +<Core/Src/*.c>
    +<Drivers/STM32F4xx_HAL_Driver/Src/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/*.c>
    +<Middlewares/ST/STM32_USB_Host_Library/Core/Src/*.c>
    +<Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/*.c>
    +<USB_HOST/Target/*.c>
    +<USB_HOST/App/*.c>
    +<Third_Party/Fusion/Fusion/*.c>
    +<Third_Party/LVGL/src/**/*.c>
    +<Third_Party/LVGL/porting/*.c>
    +<Third_Party/Lw/*.c>
    +<Third_Party/RTT/*.c>
    +<Third_Party/U8g2/*.c>
    +<Hiwonder/**/*.c>
    -<Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_msp_template.c>
    -<Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_alarm_template.c>
    -<Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_rtc_wakeup_template.c>
    -<Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_tim_template.c>
    -<Hiwonder/Misc/syscall.c>
    -<Hiwonder/LVGL_UI/lvgl_handle.c>
    -<Hiwonder/Peripherals/key.c>
    -<Core/Src/system_stm32f4xx.c>
    -<Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_conf_template.c>
    -<Hiwonder/System/checksum.c>

; 参考 MDK 的包含路径
build_unflags =
    -mfloat-abi=soft

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F407xx
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -I../Core/Inc
    -I../Drivers/STM32F4xx_HAL_Driver/Inc
    -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
    -I../Middlewares/Third_Party/FreeRTOS/Source/include
    -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -I../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc
    -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc
    -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include
    -I../Drivers/CMSIS/Include
    -I../USB_HOST/Target
    -I../USB_HOST/App
    -I../Third_Party/Fusion/Fusion
    -I../Third_Party/LVGL/porting
    -I../Third_Party/LVGL/src
    -I../Third_Party/LVGL
    -I../Third_Party/U8g2
    -I../Third_Party/RTT
    -I../Third_Party/Lw
    -I../Third_Party
    -I../Hiwonder/LVGL_UI/guider_customer_fonts
    -I../Hiwonder/LVGL_UI/guider_fonts
    -I../Hiwonder/LVGL_UI/images
    -I../Hiwonder/LVGL_UI
    -I../Hiwonder/USB_HOST
    -I../Hiwonder/Peripherals
    -I../Hiwonder/Portings
    -I../Hiwonder/Chassis
    -I../Hiwonder/System
    -I../Hiwonder/Misc

[env:release]
extends = env:stm32f407ve_base
build_type = release

[env:debug]
extends = env:stm32f407ve_base
build_type = debug
debug_build_flags =
    -O0
    -g3
