#ifndef __GLOBAL_CONF_H
#define __GLOBAL_CONF_H

#define ENABLE_DEBUG_UART    1
#define DEBUG_UART_TELEM_STATS 1
#define DEBUG_BATTERY_ADC_RAW  0

#define ENABLE_IMU  1
#define ENABLE_LVGL 0
#define ENABLE_BLUETOOTH 0
#define ENABLE_BLUETOOTH_BATTERY_REPORT 0
#define ENABLE_BATTERY_LOW_ALARM 0

#define BATTERY_LOW_ALARM_THRESHOLD 6300

#define KEY1_PUSHED_LEVEL 0
#define KEY2_PUSHED_LEVEL 0
#define LED_SYS_LEVEL_ON  0

#define LED_TASK_PERIOD     30u
#define BUZZER_TASK_PERIOD  30u
#define BUTTON_TASK_PERIOD  30u
#define BATTERY_TASK_PERIOD 50u

#define USE_PACKET_V2 1

#endif
